-- Run as a role with privileges to create database objects.

CREATE DATABASE IF NOT EXISTS WEATHER_DB;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.RAW;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.ANALYTICS;

CREATE TABLE IF NOT EXISTS WEATHER_DB.RAW.WEATHER_HOURLY_RAW (
  CITY STRING,
  LATITUDE NUMBER(9,6),
  LONGITUDE NUMBER(9,6),
  OBSERVED_AT TIMESTAMP_NTZ,
  TEMPERATURE_2M NUMBER(8,3),
  RELATIVE_HUMIDITY_2M NUMBER(8,3),
  PRECIPITATION NUMBER(8,3),
  WIND_SPEED_10M NUMBER(8,3),
  SOURCE STRING,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS WEATHER_DB.ANALYTICS.WEATHER_HOURLY (
  CITY STRING,
  LATITUDE NUMBER(9,6),
  LONGITUDE NUMBER(9,6),
  OBSERVED_AT TIMESTAMP_NTZ,
  TEMPERATURE_2M NUMBER(8,3),
  RELATIVE_HUMIDITY_2M NUMBER(8,3),
  PRECIPITATION NUMBER(8,3),
  WIND_SPEED_10M NUMBER(8,3),
  SOURCE STRING,
  INGESTED_AT TIMESTAMP_NTZ,
  CONSTRAINT PK_WEATHER_HOURLY PRIMARY KEY (CITY, OBSERVED_AT) NOT ENFORCED
);

CREATE STREAM IF NOT EXISTS WEATHER_DB.RAW.WEATHER_HOURLY_RAW_STREAM
ON TABLE WEATHER_DB.RAW.WEATHER_HOURLY_RAW;

CREATE TASK IF NOT EXISTS WEATHER_DB.RAW.TASK_MERGE_WEATHER_HOURLY
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 5 * * * * UTC'
AS
MERGE INTO WEATHER_DB.ANALYTICS.WEATHER_HOURLY t
USING (
  SELECT
    CITY,
    LATITUDE,
    LONGITUDE,
    OBSERVED_AT,
    TEMPERATURE_2M,
    RELATIVE_HUMIDITY_2M,
    PRECIPITATION,
    WIND_SPEED_10M,
    SOURCE,
    INGESTED_AT
  FROM WEATHER_DB.RAW.WEATHER_HOURLY_RAW_STREAM
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CITY, OBSERVED_AT
    ORDER BY INGESTED_AT DESC
  ) = 1
) s
ON t.CITY = s.CITY
AND t.OBSERVED_AT = s.OBSERVED_AT
WHEN MATCHED THEN UPDATE SET
  t.LATITUDE = s.LATITUDE,
  t.LONGITUDE = s.LONGITUDE,
  t.TEMPERATURE_2M = s.TEMPERATURE_2M,
  t.RELATIVE_HUMIDITY_2M = s.RELATIVE_HUMIDITY_2M,
  t.PRECIPITATION = s.PRECIPITATION,
  t.WIND_SPEED_10M = s.WIND_SPEED_10M,
  t.SOURCE = s.SOURCE,
  t.INGESTED_AT = s.INGESTED_AT
WHEN NOT MATCHED THEN INSERT (
  CITY,
  LATITUDE,
  LONGITUDE,
  OBSERVED_AT,
  TEMPERATURE_2M,
  RELATIVE_HUMIDITY_2M,
  PRECIPITATION,
  WIND_SPEED_10M,
  SOURCE,
  INGESTED_AT
) VALUES (
  s.CITY,
  s.LATITUDE,
  s.LONGITUDE,
  s.OBSERVED_AT,
  s.TEMPERATURE_2M,
  s.RELATIVE_HUMIDITY_2M,
  s.PRECIPITATION,
  s.WIND_SPEED_10M,
  s.SOURCE,
  s.INGESTED_AT
);

-- Run after validating task configuration:
-- ALTER TASK WEATHER_DB.RAW.TASK_MERGE_WEATHER_HOURLY RESUME;
